# Generated by Django 4.0.5 on 2022-06-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
